# These are supported funding model platforms

github: BTC-1Bu4CR8Bi5AXQG8pnu1avny88C5CCgWKfb
patreon: BTC- 1NEJcwfcEm7Aax8oJNjRUnY3hEavCjNrai
community_bridge: LTC LdJX6Zr43PBekv11eKBfrMtpH78qi96Mef
buy_me_a_coffee: USDT-TRON TQ1cxj8csRyWUzkonf5XgYUyFGsDJn1k7J
thanks_dev: USDT-BSC 0x3fa39005a6bb18d0e2546d97b24a767cc393b03a
